# Usa la imagen oficial de Node.js como base
FROM node:22.11-alpine3.20

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos del proyecto (excepto los ignorados en .dockerignore)
COPY package.json package-lock.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código del proyecto
COPY . .

# Expone el puerto 4200 para el servidor de Angular
EXPOSE 4200

# Comando por defecto para iniciar Angular en modo desarrollo
CMD ["npm", "run", "start"]
